site_name: Terraform GCP FinOps module
repo_name: artefactory/terraform-google-finops
repo_url: https://github.com/artefactory/terraform-google-finops

plugins:
  - techdocs-core

nav:
  - Home: index.md
  - User Guide:
      - One shot deployment: one_shot_deployment
      - Continuous deployment: continuous_deployment
